name: Build Vue
on:
  push: 
    branches: 
      - master
jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy-Vue
      uses: thefrustrateddev/github-action-test@master
      with:
        username: 'thefrustrateddev'
        reponame: 'github-action-test'
        token: ${{ secrets.GITHUB_TOKEN }}
        basebranchname: 'master'