name: Build Vue
on:
  push: 
    branches: 
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: thefrustrateddev/github-action-test@master
      with:
        username: 'thefrustrateddev'
        reponame: 'portfolio'
        token: ${{ secrets.GITHUB_TOKEN }}